// day11-ykA/koa-react/src/view/home.js
import React, {
    Component
} from 'react';
import {
    Table,Divider,Pagination, Button,Modal,Input,DatePicker, Form, Select, Cascader, InputNumber
} from 'antd';
import axios from 'axios';
import './css/home.css';
const { Option } = Select;

export default class home extends Component {
    constructor(props) {
        super(props)
        this.state = {
            columns:[{
                    title: '日期',
                    dataIndex: 'time',
                    render: text => <a> {text} </a>,
                },
                {
                    title: '标题',
                    dataIndex: 'title',
                },
                {
                    title: '作者',
                    dataIndex: 'auth',
                },
                {
                    title: '重要性',
                    dataIndex: 'isagain',
                },
                {
                    title: '阅读数',
                    dataIndex: 'num',
                },
                {
                    title: '状态',
                    dataIndex: 'status',
                },
                {
                    title: '操作',
                    render: (text, record) => ( 
                        <span>
                            <a onClick={this.edit.bind(this,text.id)}> 修改 </a> 
                            <Divider type="vertical"/>
                            <a onClick={this.del.bind(this,text.id)}> 删除 </a> 
                        </span>
                    ),
                },
            ],
            data:[],
            pageNum:1,
            limit:5,
            flag:false,
            title:'',
            auth:'',
            isagain:'',
            num:'',
            status:'',
            etid:'',
            total:0
        }
    }
    getData() {
        let {pageNum,limit}=this.state;
        axios.get('/api/list',{params:{pageNum,limit}}).then(res=>{
            if(res.data.code===1){
                this.setState({
                    data:res.data.data,
                    total:res.data.total
                })
            }
        })
    }
    //修改
    edit(id){
        this.setState({flag:true});
        let dataAll=this.state.data.find(item=>item.id===id);
        this.setState({
            title:dataAll.title,
            auth:dataAll.auth,
            isagain:dataAll.isagain,
            num:dataAll.num,
            status:dataAll.status,
            etid:dataAll.id
        })
    }
    //删除
    del(id){
        axios.get('/api/delete',{params:{id}}).then(res=>{
            if(res.data.code===1){
                this.getData();
            }
        })
    }
    //获取初始数据
    componentDidMount() {
        this.getData();
    }
    //点击弹框
    add(){
        this.initData();
        this.setState({
            flag:true
        })
    } 
    //判断是添加还是修改
    addItem(){
        let {title,auth,isagain,num,status,etid}=this.state;
        if(etid){
            //修改
            let id=etid;
            axios.post('/api/edit',{title,auth,isagain,num,status,id}).then((res)=>{
                if(res.data.code===1){
                    this.getData();
                    this.setState({
                        flag:false
                    })
                }
            })
        }else{
            //添加
            axios.post('/api/add',{title,auth,isagain,num,status}).then((res)=>{
                if(res.data.code===1){
                    this.getData();
                    this.setState({
                        flag:false
                    })
                }
            })
        }
        this.initData();
    }
    hideModal(){
        this.setState({
            flag:false
        })
    }
    //初始化数据
    initData(){
        this.setState({
            title:'',
            auth:'',
            isagain:'',
            num:'',
            status:'',
            etid:''
        })
    }
    //数据双向绑定
    Change(e){
        this.setState({
            [e.target.name]:e.target.value
        })
    }
    onChange = page => {
        this.setState({
          pageNum: page,
        });
        this.getData();
    }
    render() {
        let {title,auth,isagain,num,status,total}=this.state;
        return ( 
            <div className = "home" >
                <Button type="primary" onClick={this.add.bind(this)}>添加</Button>
                <Table columns = {this.state.columns} pagination={false} rowKey="id" dataSource = {this.state.data}/> 
                <Pagination defaultPageSize={5} current={this.state.pageNum} onChange={this.onChange} total={20} />
                <Modal
                    visible={this.state.flag}
                    onOk={this.addItem.bind(this)}
                    onCancel={this.hideModal.bind(this)}
                    okText="确认"
                    cancelText="取消"
                    >
                    <p>标题:<Input value={title} name="title" onChange={this.Change.bind(this)}/></p>
                    <p>日期:<DatePicker/></p>
                    <p>作者:<Input value={auth} name="auth" onChange={this.Change.bind(this)}/></p>
                    <p>重要性:<Input value={isagain} name="isagain" onChange={this.Change.bind(this)}/></p>
                    <p>阅读数:<Input value={num} name="num" onChange={this.Change.bind(this)}/></p>
                    <p>状态:<Input value={status} name="status" onChange={this.Change.bind(this)}/></p>
                </Modal>
            </div>
        )
    }
}

// day11-ykA/koa-vue/src/views/Home.vue
<template>
  <div class="home">
    <el-button type="primary" @click="addItem">添加</el-button>
    <el-table
    :data="tableData"
    border
    style="width: 100%">
    <el-table-column
      fixed
      prop="id"
      label="序号"
      width="150">
    </el-table-column>
    <el-table-column
      prop="time"
      label="日期"
      width="150">
    </el-table-column>
    <el-table-column
      prop="title"
      label="标题"
      width="120">
    </el-table-column>
    <el-table-column
      prop="auth"
      label="作者"
      width="120">
    </el-table-column>
    <el-table-column
      prop="isagain"
      label="重要性"
      width="120">
    </el-table-column>
    <el-table-column
      prop="num"
      label="阅读数"
      width="150">
    </el-table-column>
    <el-table-column
      prop="status"
      label="状态"
      width="120">
    </el-table-column>
    <el-table-column
      label="操作"
      width="100">
      <template slot-scope="scope">
        <el-button @click="del(scope.row.id)" type="text" size="small">删除</el-button>
        <el-button type="text" size="small" @click="edit(scope.row.id)">编辑</el-button>
      </template>
    </el-table-column>
  </el-table>
  <el-dialog
    title="添加/修改用户"
    :visible.sync="flag"
    width="30%"
    center>
    <el-form :model="ruleForm" status-icon ref="ruleForm" label-width="100px" class="demo-ruleForm">
      <el-form-item label="日期" prop="time">
        <el-date-picker
          v-model="ruleForm.time"
          type="date"
          placeholder="选择日期">
        </el-date-picker>
      </el-form-item>
      <el-form-item label="标题" prop="title">
        <el-input type="text" v-model="ruleForm.title" autocomplete="off"></el-input>
      </el-form-item>
      <el-form-item label="作者" prop="auth">
        <el-input type="text" v-model="ruleForm.auth" autocomplete="off"></el-input>
      </el-form-item>
      <el-form-item label="重要性" prop="isagain">
        <el-input type="text" v-model="ruleForm.isagain" autocomplete="off"></el-input>
      </el-form-item>
      <el-form-item label="阅读数" prop="num">
        <el-input type="text" v-model="ruleForm.num" autocomplete="off"></el-input>
      </el-form-item>
      <el-form-item prop="status">
        <el-radio-group v-model="ruleForm.status">
          <el-radio label="draft">draft</el-radio>
          <el-radio label="published">published</el-radio>
        </el-radio-group>
      </el-form-item>
    </el-form>
    <span slot="footer" class="dialog-footer">
      <el-button type="primary" @click="add">{{editId?'修改':'添加'}}</el-button>
    </span>
  </el-dialog>
  <el-pagination
    background
    :page-size="limit"
    layout="prev, pager, next"
    @current-change="handleCurrentChange"
    :total="total">
  </el-pagination>
  </div>
</template>
<script>
export default {
  data(){
    return {
      tableData: [],
      pageNum:1,
      limit:5,
      flag: false,
      ruleForm:{
        time:'',
        title:'',
        auth:'',
        isagain:'',
        num:'',
        status:''
      },
      editId:'',
      total:0
    }
  },
  methods:{
    //当前显示第几页
    handleCurrentChange(val) {
      this.pageNum=val;
      this.getData();
    },
    //删除
    del(id) {
      this.axios.get('/api/delete',{params:{id}}).then((res)=>{
        if(res.data.code===1){
          this.getData();
        }
      })
    },
    //获取数据
    getData(){
      let {pageNum,limit}=this;
      this.axios.get('/api/list',{params:{pageNum,limit}}).then((res)=>{
        console.log(res)
        this.tableData=res.data.data;
        this.total=res.data.total;
      })
    },
   
    //点击添加弹出遮罩层
    addItem(){
      this.flag=true;
      this.reset();
    },
    //修改
    edit(id){
      this.flag=true;
      let editObj = this.tableData.find(item => item.id === id);
      this.ruleForm.time = editObj.time;
      this.ruleForm.title = editObj.title;
      this.ruleForm.auth = editObj.auth;
      this.ruleForm.isagain = editObj.isagain;
      this.ruleForm.num = editObj.num;
      this.ruleForm.status = editObj.status;
      this.editId = editObj.id;
    },
    //点击确定根据editId判断是修改还是删除
    add(){
      if(this.editId){
        //如果editId有值就修改
        this.axios.post('/api/edit',{...this.ruleForm,id:this.editId}).then((res)=>{
          if(res.data.code===1){
            this.getData();
          }
        })
      }else{
        //如果editId没有值就添加
        this.axios.post('/api/add',{...this.ruleForm}).then((res)=>{
          if(res.data.code===1){
            this.getData();
          }
        })
      }
      this.reset();
      this.flag=false;
    },
    //清空input框
    reset(){
      this.ruleForm = {
        time:'',
        title:'',
        auth:'',
        isagain:'',
        num:'',
        status:''
      },
      this.editId='';
    },
  },
  created(){
    this.getData();
  }
}
</script>
<style scoped lang="scss">
  .home{
    width:100%;
    height:100%;
  }
  .p{
    width: 100%;
    height: 35px;
    text-align: center;
    button{
        width: 80px;
        height: 30px;
        line-height: 30px;
        border:none;
        background: rgb(233, 78, 6);
        color:white;
        margin-left: 5px;
    }
    span{
        display: inline-block;
        width: 35px;
        height: 35px;
        line-height: 35px;
        text-align: center;
        border:1px solid #ccc;
    }
  }
</style>
